//! Serve the embedded frontend (SPA + static assets) from the API binary.
//!
//! The compiled WASM frontend (`parser-web/dist`) is embedded at build time by
//! `build.rs` into `embedded_assets.rs`. This module exposes Rocket handlers
//! that:
//!   * serve `/` with the SPA entry `index.html`,
//!   * serve known static asset paths (wasm/js/css/…),
//!   * act as the SPA client-side-router fallback: any non-`/api` GET that does
//!     not match a real file returns `index.html` so client navigation works.
//!
//! Cache headers mirror the previous nginx config:
//!   * hashed build artifacts (16-hex/8-hex filename chunk, and `.wasm`) →
//!     `Cache-Control: public, max-age=31536000, immutable`
//!   * `static/config.js` (mutable conf) → `no-store, no-cache`
//!   * `index.html` → `no-cache` (must revalidate so a new build is picked up)
//!   * everything else → short default.

use std::borrow::Cow;
use std::io::Cursor;

use rocket::http::uri::Segments;
use rocket::http::uri::fmt::Path;
use rocket::http::{ContentType, Status};
use rocket::request::Request;
use rocket::response::{self, Responder, Response};

// Generated by build.rs: `EMBEDDED`, `FALLBACK_HTML`, `ASSETS`, `Asset`.
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// Thin responder that renders an embedded file with a cached content-type,
/// status and cache-control header (plus an optional extra header).
pub struct EmbeddedFile {
    status: Status,
    content_type: ContentType,
    body: &'static [u8],
    cache: Cow<'static, str>,
    /// Optional extra header, e.g. `Service-Worker-Allowed`.
    extra: Option<(&'static str, &'static str)>,
}

impl<'r> Responder<'r, 'static> for EmbeddedFile {
    fn respond_to(self, _: &'r Request<'_>) -> response::Result<'static> {
        match self.extra {
            Some((name, value)) => Ok(Response::build()
                .status(self.status)
                .header(self.content_type)
                .sized_body(self.body.len(), Cursor::new(self.body))
                .raw_header("Cache-Control", self.cache)
                .raw_header(name, value)
                .finalize()),
            None => Ok(Response::build()
                .status(self.status)
                .header(self.content_type)
                .sized_body(self.body.len(), Cursor::new(self.body))
                .raw_header("Cache-Control", self.cache)
                .finalize()),
        }
    }
}
fn index_payload() -> Option<&'static [u8]> {
    if !EMBEDDED {
        return None;
    }
    for a in ASSETS {
        if a.path == "index.html" {
            return Some(a.data);
        }
    }
    if !FALLBACK_HTML.is_empty() {
        Some(FALLBACK_HTML.as_bytes())
    } else {
        None
    }
}

/// Look up an embedded asset by its dist-relative path (no leading `/`).
fn lookup(path: &str) -> Option<&'static Asset> {
    let key = path.trim_start_matches('/');
    if key.is_empty() || key.contains("..") || key.contains('\\') {
        return None;
    }
    ASSETS.iter().find(|a| a.path == key)
}

/// Map a file extension to a content type.
fn content_type_for(path: &str) -> ContentType {
    let ext = path.rsplit('.').next().unwrap_or("");
    match ext {
        "wasm" => ContentType::new("application", "wasm"),
        "js" => ContentType::JavaScript,
        "mjs" => ContentType::JavaScript,
        "css" => ContentType::CSS,
        "html" | "htm" => ContentType::HTML,
        "svg" => ContentType::new("image", "svg+xml"),
        "png" => ContentType::PNG,
        "ico" => ContentType::new("image", "x-icon"),
        "json" => ContentType::JSON,
        "txt" => ContentType::Plain,
        "xml" => ContentType::new("text", "xml"),
        "pdf" => ContentType::PDF,
        "woff2" => ContentType::new("font", "woff2"),
        "woff" => ContentType::new("font", "woff"),
        "ttf" => ContentType::new("font", "ttf"),
        "map" => ContentType::new("application", "json"),
        _ => ContentType::new("application", "octet-stream"),
    }
}

/// True for immutable, long-cacheable artifacts (content-hashed or `.wasm`).
fn is_immutable_hash(path: &str) -> bool {
    if path.ends_with(".wasm") {
        return true;
    }
    if let Some(name) = path.rsplit('/').next()
        && let Some((stem, _)) = name.rsplit_once('.')
        && let Some(hash) = stem.rsplit('-').next()
        && hash.len() >= 8
        && hash.chars().all(|c| c.is_ascii_hexdigit())
    {
        return true;
    }
    false
}

/// Build an [`EmbeddedFile`] for `body` with the requested cache hint.
fn file_response(
    body: &'static [u8],
    content_type: ContentType,
    cache: &'static str,
) -> EmbeddedFile {
    EmbeddedFile {
        status: Status::Ok,
        content_type,
        body,
        cache: Cow::Borrowed(cache),
        extra: None,
    }
}

/// Serve the SPA entry (`/`).
#[rocket::get("/")]
pub fn index() -> EmbeddedFile {
    match index_payload() {
        Some(body) => file_response(body, ContentType::HTML, "no-cache"),
        None => EmbeddedFile {
            status: Status::ServiceUnavailable,
            content_type: ContentType::Plain,
            body: b"Frontend not embedded. Build parser-web (trunk build --release) before building the API.\n",
            cache: Cow::Borrowed("no-cache"),
            extra: None,
        },
    }
}

/// Serve a static asset or, for unknown non-`/api` paths, the SPA fallback.
#[rocket::get("/<path..>")]
pub fn files(path: Segments<'_, Path>) -> EmbeddedFile {
    // Collect path segments into a `/`-joined relative path.
    let raw: String = path.into_iter().collect::<Vec<_>>().join("/");

    // Never let the SPA swallow `/api/*` — the API mount/catchers own it.
    if raw == "api" || raw.starts_with("api/") {
        return not_found();
    }

    if let Some(asset) = lookup(&raw) {
        let ct = content_type_for(asset.path);
        let immutable = is_immutable_hash(asset.path);
        let no_store = asset.path == "static/config.js" || asset.path == "config.js";
        let hint = if no_store {
            "no-store, no-cache, must-revalidate, max-age=0"
        } else if immutable {
            "public, max-age=31536000, immutable"
        } else {
            "public, max-age=300"
        };
        return file_response(asset.data, ct, hint);
    }

    // SPA client-side router fallback for paths with no file extension.
    if !raw.to_ascii_lowercase().contains('.')
        && let Some(body) = index_payload()
    {
        return file_response(body, ContentType::HTML, "no-cache");
    }

    not_found()
}

fn not_found() -> EmbeddedFile {
    EmbeddedFile {
        status: Status::NotFound,
        content_type: ContentType::Plain,
        body: b"Not found\n",
        cache: Cow::Borrowed("no-cache"),
        extra: None,
    }
}

/// Serve the Service Worker from the root path so its scope covers the whole
/// origin (no `Service-Worker-Allowed` header is needed at `/`).
#[rocket::get("/sw.js")]
pub fn service_worker() -> EmbeddedFile {
    if let Some(asset) = lookup("static/sw.js") {
        EmbeddedFile {
            status: Status::Ok,
            content_type: ContentType::JavaScript,
            body: asset.data,
            cache: Cow::Borrowed("no-cache"),
            extra: Some(("Service-Worker-Allowed", "/")),
        }
    } else {
        not_found()
    }
}

/// Rocket routes for the SPA root path. Callers mount at `/`.
pub fn routes() -> Vec<rocket::Route> {
    rocket::routes![index, files, service_worker]
}

#[cfg(test)]
mod tests {
    use super::routes;
    use rocket::http::{ContentType, Status};
    use rocket::local::blocking::Client;

    fn client() -> Client {
        Client::tracked(rocket::build().mount("/", routes())).expect("rocket client")
    }

    #[test]
    fn serves_index() {
        if !super::EMBEDDED {
            eprintln!("skipping: frontend not embedded in this build");
            return;
        }
        let c = client();
        let r = c.get("/").dispatch();
        assert_eq!(r.status(), Status::Ok);
        assert_eq!(r.content_type(), Some(ContentType::HTML));
        let cache = r.headers().get_one("Cache-Control").unwrap_or("");
        assert!(
            cache.contains("no-cache"),
            "index should be no-cache, got {cache}"
        );
        let body = String::from_utf8(r.into_bytes().unwrap()).unwrap();
        assert!(body.contains("<html"), "expected HTML, got non-HTML body");
    }

    #[test]
    fn serves_static_and_hashed_asset() {
        if !super::EMBEDDED {
            eprintln!("skipping: frontend not embedded in this build");
            return;
        }
        let c = client();
        // config.js is mutable -> no-store.
        let r = c.get("/static/config.js").dispatch();
        assert_eq!(r.status(), Status::Ok);
        let cc = r.headers().get_one("Cache-Control").unwrap_or("");
        assert!(
            cc.contains("no-store"),
            "config.js should be no-store, got {cc}"
        );

        // A hashed wasm asset -> immutable, correct content type.
        let wasm = super::ASSETS
            .iter()
            .find(|a| a.path.ends_with(".wasm"))
            .map(|a| a.path)
            .expect("wasm asset present");
        let r = c.get(format!("/{wasm}")).dispatch();
        assert_eq!(r.status(), Status::Ok);
        assert_eq!(
            r.content_type(),
            Some(ContentType::new("application", "wasm"))
        );
        let cc = r.headers().get_one("Cache-Control").unwrap_or("");
        assert!(
            cc.contains("immutable"),
            "wasm should be immutable, got {cc}"
        );
    }

    #[test]
    fn spa_fallback_for_client_route() {
        if !super::EMBEDDED {
            eprintln!("skipping: frontend not embedded in this build");
            return;
        }
        let c = client();
        // A client-side route (no file extension) falls back to index.html.
        let r = c.get("/account/123").dispatch();
        assert_eq!(r.status(), Status::Ok);
        assert_eq!(r.content_type(), Some(ContentType::HTML));
    }

    #[test]
    fn api_guard_not_served_as_spa() {
        // Even when embedded, `/api/*` must not be swallowed by the SPA handler.
        let c = client();
        let r = c.get("/api/anything").dispatch();
        assert_eq!(r.status(), Status::NotFound);
    }

    #[test]
    fn unknown_file_extension_404() {
        let c = client();
        let r = c.get("/nope.js").dispatch();
        assert_eq!(r.status(), Status::NotFound);
    }

    #[test]
    fn serves_manifest_and_pwa_icons() {
        if !super::EMBEDDED {
            eprintln!("skipping: frontend not embedded in this build");
            return;
        }
        let c = client();
        let r = c.get("/static/manifest.json").dispatch();
        assert_eq!(r.status(), Status::Ok);
        assert_eq!(r.content_type(), Some(ContentType::JSON));
        let body = String::from_utf8(r.into_bytes().unwrap()).unwrap();
        assert!(body.contains("\"short_name\""));

        let r = c.get("/static/pwa/icon-192.png").dispatch();
        assert_eq!(r.status(), Status::Ok);
        assert_eq!(r.content_type(), Some(ContentType::PNG));
    }

    #[test]
    fn serves_service_worker_at_root_scope() {
        if !super::EMBEDDED {
            eprintln!("skipping: frontend not embedded in this build");
            return;
        }
        if super::lookup("static/sw.js").is_none() {
            eprintln!("skipping: static/sw.js not present in embedded assets");
            return;
        }
        let c = client();
        let r = c.get("/sw.js").dispatch();
        assert_eq!(r.status(), Status::Ok);
        assert_eq!(r.content_type(), Some(ContentType::JavaScript));
        let allowed = r.headers().get_one("Service-Worker-Allowed");
        assert_eq!(allowed, Some("/"), "SW should be served with root scope");
        // Must not be treated as the SPA fallback.
        let cc = r.headers().get_one("Cache-Control").unwrap_or("");
        assert!(cc.contains("no-cache"));
    }
}

#[cfg(test)]
mod api_mount_tests {
    // Verify mounting the SPA wildcard at `/` alongside an `/api` mount causes
    // no route collision and that `/api/*` still routes to the API, not the SPA.

    #[rocket::get("/ping")]
    fn ping() -> &'static str {
        "pong"
    }

    #[test]
    fn no_route_collision_and_api_precedence() {
        use rocket::local::blocking::Client;
        let rocket = rocket::build()
            .mount("/", super::routes())
            .mount("/api", rocket::routes![ping]);
        let c = Client::tracked(rocket).expect("client builds without route collision");

        // `/api/*` resolves to the API route (more specific mount wins).
        let r = c.get("/api/ping").dispatch();
        assert_eq!(r.status(), rocket::http::Status::Ok);
        assert_eq!(String::from_utf8(r.into_bytes().unwrap()).unwrap(), "pong");

        // Root path serves the SPA.
        let r = c.get("/").dispatch();
        assert_eq!(r.status(), rocket::http::Status::Ok);
    }
}
