//! build.rs — embeds the compiled frontend (`parser-web/dist`) into the API
//! binary so it can serve the SPA and its static assets directly, without a
//! separate nginx/document-root.
//!
//! Strategy: at build time we scan `../parser-web/dist` (relative to this
//! manifest) and generate a Rust module under `$OUT_DIR/embedded_assets.rs`
//! that:
//!   * `pub const EMBEDDED: bool` — whether the frontend was found.
//!   * `pub static FALLBACK_HTML: &str` — the SPA entry `index.html` (used by
//!     the client-side-router fallback for unknown `/`-rooted paths).
//!   * `pub static ASSETS: &[Asset]` — every file with `path` (relative to the
//!     dist root, no leading `/`) and `data`.
//!
//! If the dist directory is absent (e.g. a dev `cargo check` or a build meant
//! to run the API without the frontend), it generates an empty table with
//! `EMBEDDED = false`, so the server still compiles and serves `/api` while a
//! thin message stands in for the SPA. This keeps dev builds fast and avoids a
//! hard build-time dependency on trunk.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=PARSER_WEB_DIST");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    // Allow overriding the dist path (e.g. docker builds that copy dist in).
    let dist = env::var("PARSER_WEB_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("../parser-web/dist"));

    println!("cargo:rerun-if-changed={}", dist.display());

    let generated = render(&dist);
    fs::write(out_dir.join("embedded_assets.rs"), generated)
        .expect("failed to write embedded_assets.rs");
}

/// Recursively collect all files under `root`, returning relative paths
/// (POSIX separators, no leading `/`) alongside their absolute source path.
fn collect(root: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    fn walk(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
        let Ok(rd) = fs::read_dir(dir) else { return };
        for entry in rd.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, root, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .expect("path is relative to root")
                    .to_string_lossy()
                    .replace('\\', "/");
                // Skip pre-compressed copies (`.gz`/`.br` produced by the
                // `compress-dist` hook): they would double binary size and
                // embedded serving hands over raw bytes anyway.
                if rel.ends_with(".gz") || rel.ends_with(".br") || rel.ends_with(".zst") {
                    continue;
                }
                out.push((rel, path));
            }
        }
    }
    walk(root, root, &mut out);
    out
}

fn render(dist: &Path) -> String {
    let mut s = String::new();
    s.push_str("// @generated by parser-api/build.rs — do not edit.\n\n");

    if !dist.is_dir() {
        s.push_str("// Frontend dist not found at build time; running without embedded SPA.\n");
        s.push_str("pub const EMBEDDED: bool = false;\n");
        s.push_str("pub static FALLBACK_HTML: &str = \"\";\n");
        s.push_str("pub static ASSETS: &[Asset] = &[];\n");
        s.push_str("pub struct Asset { pub path: &'static str, pub data: &'static [u8] }\n");
        return s;
    }

    let files = collect(dist);
    // Deterministic ordering so binary layout is stable across rebuilds.
    let mut files = files;
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let mut fallback_html = String::new();
    let mut assets = String::new();
    assets.push_str("pub struct Asset { pub path: &'static str, pub data: &'static [u8] }\n");
    assets.push_str("pub static ASSETS: &[Asset] = &[\n");

    for (idx, (rel, abs)) in files.iter().enumerate() {
        let abs_str = abs.to_string_lossy();
        let data_ident = format!("A{idx}");
        writeln!(s, "#[allow(non_upper_case_globals)]").unwrap();
        writeln!(
            s,
            "static {data_ident}: &[u8] = include_bytes!({abs_str:?});"
        )
        .unwrap();

        if rel == "index.html" {
            writeln!(s, "pub static FALLBACK_HTML: &str = ").unwrap();
            // Copy bytes as a UTF-8 literal (index.html is small & ASCII-ish).
            let bytes = fs::read(abs).expect("read index.html");
            let _ = write_escaped(&mut s, &bytes);
            s.push_str(";\n");
            fallback_html = rel.clone();
        }

        writeln!(assets, "    Asset {{ path: {rel:?}, data: {data_ident} }},").unwrap();
    }

    // Ensure a fallback even if index.html wasn't among collected files.
    if fallback_html.is_empty() {
        s.push_str("pub static FALLBACK_HTML: &str = \"\";\n");
    }

    assets.push_str("];\n");
    s.push_str(&assets);
    s.push_str("pub const EMBEDDED: bool = true;\n");
    s
}

/// Write bytes as an escaped Rust string literal (handles non-UTF8 by using
/// byte escapes so the generated source stays valid).
fn write_escaped(out: &mut String, bytes: &[u8]) -> Result<(), std::fmt::Error> {
    out.push('"');
    for &b in bytes {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(b as char),
            _ => write!(out, "\\x{b:02x}")?,
        }
    }
    out.push('"');
    Ok(())
}
