services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8181:8080"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./Rocket.toml:/app/Rocket.toml:ro
      - ./database.db:/app/database.db:ro
    environment:
      - CONFIG_PATH=/app/config.toml
